spring:
  application:
    name: brand-service
  messages:
    basename: i18n/messages
    default-encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/brand-db
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1800000
      auto-commit: true

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      show-sql: true
server:
  port: 8085
